# Generated by Django 3.2.21 on 2023-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
