# Generated by Django 3.2.21 on 2023-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreservation',
            name='reversed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
