# Generated by Django 3.2.21 on 2023-09-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_alter_productreservation_reversed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReservation',
        ),
    ]
