# Generated by Django 3.2.21 on 2023-09-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230913_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colour',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='colour',
            new_name='color',
        ),
    ]
