# Generated by Django 3.2.21 on 2023-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230916_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
