# Generated by Django 3.2.21 on 2023-09-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order']},
        ),
    ]
